//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/superproj/onex.

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	apps "github.com/superproj/k8sdemo/resourcedefinition/apps"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*XXX)(nil), (*apps.XXX)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_XXX_To_apps_XXX(a.(*XXX), b.(*apps.XXX), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apps.XXX)(nil), (*XXX)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apps_XXX_To_v1beta1_XXX(a.(*apps.XXX), b.(*XXX), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*XXXList)(nil), (*apps.XXXList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_XXXList_To_apps_XXXList(a.(*XXXList), b.(*apps.XXXList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apps.XXXList)(nil), (*XXXList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apps_XXXList_To_v1beta1_XXXList(a.(*apps.XXXList), b.(*XXXList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*XXXSpec)(nil), (*apps.XXXSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_XXXSpec_To_apps_XXXSpec(a.(*XXXSpec), b.(*apps.XXXSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apps.XXXSpec)(nil), (*XXXSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apps_XXXSpec_To_v1beta1_XXXSpec(a.(*apps.XXXSpec), b.(*XXXSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*XXXStatus)(nil), (*apps.XXXStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_XXXStatus_To_apps_XXXStatus(a.(*XXXStatus), b.(*apps.XXXStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apps.XXXStatus)(nil), (*XXXStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_apps_XXXStatus_To_v1beta1_XXXStatus(a.(*apps.XXXStatus), b.(*XXXStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_XXX_To_apps_XXX(in *XXX, out *apps.XXX, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_XXXSpec_To_apps_XXXSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_XXXStatus_To_apps_XXXStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_XXX_To_apps_XXX is an autogenerated conversion function.
func Convert_v1beta1_XXX_To_apps_XXX(in *XXX, out *apps.XXX, s conversion.Scope) error {
	return autoConvert_v1beta1_XXX_To_apps_XXX(in, out, s)
}

func autoConvert_apps_XXX_To_v1beta1_XXX(in *apps.XXX, out *XXX, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_apps_XXXSpec_To_v1beta1_XXXSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_apps_XXXStatus_To_v1beta1_XXXStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_apps_XXX_To_v1beta1_XXX is an autogenerated conversion function.
func Convert_apps_XXX_To_v1beta1_XXX(in *apps.XXX, out *XXX, s conversion.Scope) error {
	return autoConvert_apps_XXX_To_v1beta1_XXX(in, out, s)
}

func autoConvert_v1beta1_XXXList_To_apps_XXXList(in *XXXList, out *apps.XXXList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]apps.XXX)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_XXXList_To_apps_XXXList is an autogenerated conversion function.
func Convert_v1beta1_XXXList_To_apps_XXXList(in *XXXList, out *apps.XXXList, s conversion.Scope) error {
	return autoConvert_v1beta1_XXXList_To_apps_XXXList(in, out, s)
}

func autoConvert_apps_XXXList_To_v1beta1_XXXList(in *apps.XXXList, out *XXXList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]XXX)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_apps_XXXList_To_v1beta1_XXXList is an autogenerated conversion function.
func Convert_apps_XXXList_To_v1beta1_XXXList(in *apps.XXXList, out *XXXList, s conversion.Scope) error {
	return autoConvert_apps_XXXList_To_v1beta1_XXXList(in, out, s)
}

func autoConvert_v1beta1_XXXSpec_To_apps_XXXSpec(in *XXXSpec, out *apps.XXXSpec, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Description = in.Description
	return nil
}

// Convert_v1beta1_XXXSpec_To_apps_XXXSpec is an autogenerated conversion function.
func Convert_v1beta1_XXXSpec_To_apps_XXXSpec(in *XXXSpec, out *apps.XXXSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_XXXSpec_To_apps_XXXSpec(in, out, s)
}

func autoConvert_apps_XXXSpec_To_v1beta1_XXXSpec(in *apps.XXXSpec, out *XXXSpec, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Description = in.Description
	return nil
}

// Convert_apps_XXXSpec_To_v1beta1_XXXSpec is an autogenerated conversion function.
func Convert_apps_XXXSpec_To_v1beta1_XXXSpec(in *apps.XXXSpec, out *XXXSpec, s conversion.Scope) error {
	return autoConvert_apps_XXXSpec_To_v1beta1_XXXSpec(in, out, s)
}

func autoConvert_v1beta1_XXXStatus_To_apps_XXXStatus(in *XXXStatus, out *apps.XXXStatus, s conversion.Scope) error {
	out.Phase = apps.XXXPhase(in.Phase)
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_XXXStatus_To_apps_XXXStatus is an autogenerated conversion function.
func Convert_v1beta1_XXXStatus_To_apps_XXXStatus(in *XXXStatus, out *apps.XXXStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_XXXStatus_To_apps_XXXStatus(in, out, s)
}

func autoConvert_apps_XXXStatus_To_v1beta1_XXXStatus(in *apps.XXXStatus, out *XXXStatus, s conversion.Scope) error {
	out.Phase = XXXPhase(in.Phase)
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_apps_XXXStatus_To_v1beta1_XXXStatus is an autogenerated conversion function.
func Convert_apps_XXXStatus_To_v1beta1_XXXStatus(in *apps.XXXStatus, out *XXXStatus, s conversion.Scope) error {
	return autoConvert_apps_XXXStatus_To_v1beta1_XXXStatus(in, out, s)
}
