---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-math-superproj-com-v1-calculate
  failurePolicy: Fail
  name: mcalculate.kb.io
  rules:
  - apiGroups:
    - math.superproj.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - calculates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-math-superproj-com-v1-calculate
  failurePolicy: Fail
  name: vcalculate.kb.io
  rules:
  - apiGroups:
    - math.superproj.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - calculates
  sideEffects: None
