# permissions for end users to view sums.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: using-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: sum-viewer-role
rules:
- apiGroups:
  - calculator.superproj.com
  resources:
  - sums
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - calculator.superproj.com
  resources:
  - sums/status
  verbs:
  - get
