# permissions for end users to view calculates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: webhook-with-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: calculate-viewer-role
rules:
- apiGroups:
  - math.superproj.com
  resources:
  - calculates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - math.superproj.com
  resources:
  - calculates/status
  verbs:
  - get
