apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-example-cfg
  labels:
    app: admission-webhook-example
webhooks:
  - name: mutating-example.qikqiak.com
    clientConfig:
      service:
        name: admission-webhook-example-svc
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxRENDQXBDZ0F3SUJBZ0lVTjArNGRNOUZmR3c0VXdTK0lJQ0NsUGZhdTE0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2F6RUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVTTUJBR0ExVUVDeE1KYzNWd1pYSndjbTlxTVJZd0ZBWURWUVFECkV3MXJkV0psY201bGRHVnpMV05oTUNBWERUSTBNRFV5TlRBek1UUXdNRm9ZRHpJeE1qUXdOVEF4TURNeE5EQXcKV2pCck1Rc3dDUVlEVlFRR0V3SkRUakVRTUE0R0ExVUVDQk1IUW1WcFNtbHVaekVRTUE0R0ExVUVCeE1IUW1WcApTbWx1WnpFTU1Bb0dBMVVFQ2hNRGF6aHpNUkl3RUFZRFZRUUxFd2x6ZFhCbGNuQnliMm94RmpBVUJnTlZCQU1UCkRXdDFZbVZ5Ym1WMFpYTXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzcKUHZYNkp5NWtFdy9WUEFNZU10VmpzbkIwZVlZWEl1dG5PaUtsRXRwMXp1a2FLZ0ZRa3JjNCswaldWOTQrclJoUwpJRllSaXVGTVFBc242b1RnNlJnVDhnWVlCTFBFNms0OE94azNSVmxNc0QyTkozZ0xsTHRrK29xaVdyVitoQUd2CjJmVnk4Vmo4dmRWbWYzR1dnR2V0R1B3YUk0ZE1JSTdadDkwUk0wczJhWnVaanY1NVRVdkpacStvZGZxTG5wbmMKZjExVUZ1UytNZVZlei9ER1FzbGZnKzdHZEFjVExzdGZIQnNmUVJXU3VhdXFkbWI3VlF3a08wOWsrcXpGMGsrVQpHNFBjbnB0eVZRRU1zVlIyL3hvd0p2a1pDUnpsdkVrUVFnMzVZQVh6U0hFRDhMSVdGdzdiam82TlVxSUYycGFvCkF5NE5acCtaOXhRemIrSFdwUzREQWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUJCakFQQmdOVkhSTUIKQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUck5TVS9KaUR2dHNhM3BROThrREZPVk9hOWhUQU5CZ2txaGtpRwo5dzBCQVFzRkFBT0NBUUVBbWoxNUZaNjJnclIxUmJoWUYyWjVUOHV3c2p1cE8wV0I0U2NyOVBtZ2x1WEZDMXFGCm5YSURjWGQ5UXIyemJYeEdSeXlTNTU3eDJqcFZRUkU1THNFOTRoMFRocUk0clMyVnFpRklic09YZTJBM2g5dnEKNkZrbm1ZNGVEbk15QlV3ZjMwc1dnVVZucGszOEx5NWFtVFVweVU0MGtERUJRcEpnN3Zta003YXFXNVlTWG11QQpGRCtMMHoxK3VpNmNGWFVRYmUyM0RpOGc4Tnk0c1NmZEhiVDBYOXFaRWZWREtRekN3NUJqVmw2NU1rOUNvdFlhCk5JYlE4Mjc0Z0FEMnk2QlVMQlV0UTF3clU1TzJTcCtheEY3NjNGZ2JCTUpxTGY5d3BPeVJsb0QrTXpWSVJDMWgKRmRQK1ErTXIrM2xwaEw4NFI4OFVNSy9aZVFUN2NZeTIzbk5BN3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","services"]
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    namespaceSelector:
      matchLabels:
        admission-webhook-example: enabled

