apiVersion: apiregistration.k8s.io/v1  
kind: APIService  
metadata:  
  name: v1.example.com  
spec:  
  service:  
    name: aggregated-service
    namespace: default  
  group: example.com  
  version: v1  
  groupPriorityMinimum: 100  
  versionPriority: 100
  insecureSkipTLSVerify: true
